version: '3.8'

services:
  app:
    build: .
    container_name: pixelmap
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-8080}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped